#!/bin/bash

set -euo pipefail

# Magic header to identify files generated by this script
MAGIC_HEADER="/* created by barrel.sh */"

################################################################################
# Displays comprehensive help information.
################################################################################

show_help() {
  cat <<EOF
barrel - Generate Dart barrel (export) files

DESCRIPTION
  Creates barrel files that re-export all Dart files in a directory tree.
  Barrel files simplify imports by allowing you to import an entire folder's
  contents from a single file. Also supports deleting generated barrel files.

USAGE
  barrel <command> [options]

COMMANDS
  create            Create barrel files for the specified folder
  delete            Delete barrel files that were created by this script

OPTIONS
  --folder=PATH     Folder to process (default: current directory)
  --target=NAME     Name for the root barrel file (default: folder name)
  --yes             Skip confirmation prompts
  --quiet           Suppress all output (implies --yes)
  --help            Show this help message and exit

GENERATED FILES
  - Root file: <target>.dart in current directory
  - Per-folder: exports_<foldername>.dart in each subdirectory

SAFETY
  Only files with the magic header "/* created by barrel.sh */" will be
  deleted. Hand-written files are never touched.

EXCLUDED FROM EXPORTS
  - Files matching exports_*.dart (other barrel files)
  - Files matching *.g.dart (generated code)
  - Files created by barrel.sh (contain magic header)

EXAMPLES
  barrel create --folder=lib --yes
  barrel create --folder=src --target=my_library
  barrel delete --folder=lib --quiet

EOF
  exit 0
}


################################################################################
# Parses command line arguments and sets global variables.
#
# Arguments:
#   $@ - Command line arguments passed to the script.
# Outputs:
#   Sets globals: VERB, FOLDER, TARGET_NAME, YES, QUIET.
################################################################################

parse_arguments() {
  if [ $# -eq 0 ]; then
    echo "Error: Missing command."
    show_help
  fi

  VERB="$1"
  shift

  FOLDER="."
  TARGET_NAME=""
  YES=false
  QUIET=false

  for arg in "$@"; do
    case $arg in
      --folder=*) FOLDER="${arg#*=}" ;;
      --target=*) TARGET_NAME="${arg#*=}" ;;
      --yes)      YES=true ;;
      --quiet)    QUIET=true; YES=true ;;
      --help)     show_help ;;
      *)          echo "Error: Unknown option $arg"; show_help ;;
    esac
  done

  FOLDER="${FOLDER%/}"
}

################################################################################
# Determines the full path for the root barrel file based on inputs.
#
# Arguments:
#   None (Uses global FOLDER and TARGET_NAME)
# Outputs:
#   Sets global ROOT_FILE.
################################################################################

determine_root_filename() {
  if [ -z "$TARGET_NAME" ]; then
    if [ "$FOLDER" = "." ]; then
      TARGET_NAME="barrel"
    else
      TARGET_NAME=$(basename "$FOLDER")
    fi
  fi

  if [[ ! "$TARGET_NAME" =~ \.dart$ ]]; then
    TARGET_NAME="${TARGET_NAME}.dart"
  fi

  ROOT_FILE="./$TARGET_NAME"
}

################################################################################
# Checks if a file contains the magic header indicating it was created by this 
# script.
#
# Arguments:
#   $1 - Path to the file to check.
# Returns:
#   0 if safe to delete (header matches), 1 otherwise.
################################################################################

is_safe_to_delete() {
  local file="$1"
  if [ -f "$file" ]; then
    local header
    header=$(head -n 1 "$file")
    if [ "$header" = "$MAGIC_HEADER" ]; then
      return 0
    fi
  fi
  return 1
}

################################################################################
# Recursively generates barrel files.
# If an output_file is provided, it writes to that specific file.
# If not, it generates the standard 'exports_<dirname>.dart' inside the 
# directory.
#
# Arguments:
#   $1 - Directory to process.
#   $2 - (Optional) Explicit output filename. If empty, auto-generates name.
# Outputs:
#   Creates the barrel file and recursively processes subdirectories.
################################################################################

generate_recursive() {
  local dir="$1"
  local explicit_output="$2"
  local output_file
  local base_name
  
  base_name=$(basename "$dir")

  if [ -n "$explicit_output" ]; then
    output_file="$explicit_output"
  else
    output_file="$dir/exports_${base_name}.dart"
  fi

  {
    echo "$MAGIC_HEADER"
    echo ""

    for f in "$dir"/*.dart; do
      [ -e "$f" ] || continue
      local fname
      fname=$(basename "$f")

      if [[ "$dir/$fname" == "$output_file" ]] || [[ "./$fname" == "$output_file" ]]; then
        continue
      fi

      if [[ "$fname" == exports_*.dart ]]; then
        continue
      fi

      if [[ "$fname" == *.g.dart ]]; then
        continue
      fi

      local header
      header=$(head -n 1 "$f")
      if [[ "$header" == "$MAGIC_HEADER" ]]; then
        continue
      fi

      echo "export \"$fname\";"
    done

    for d in "$dir"/*/; do
      [ -d "$d" ] || continue
      d="${d%/}"
      local sub_name
      sub_name=$(basename "$d")
      
      generate_recursive "$d" ""
      
      echo "export \"$sub_name/exports_${sub_name}.dart\";"
    done
  } > "$output_file"
}

################################################################################
# Orchestrates the deletion of the root file and recursive export files.
#
# Arguments:
#   None (Uses globals)
# Outputs:
#   Deletes files and writes status to stdout.
################################################################################

perform_delete() {
  if [ "$QUIET" = false ]; then
    echo "--------------------------------------------------"
    echo "Deleting barrel files..."
    echo "  Root: $ROOT_FILE"
    echo "  Scan: $FOLDER"
    echo "--------------------------------------------------"
  fi

  if [ "$YES" = false ]; then
    read -p "Delete generated files? [y/N] " -n 1 -r
    echo ""
    [[ $REPLY =~ ^[Yy]$ ]] || exit 0
  fi

  if is_safe_to_delete "$ROOT_FILE"; then
    rm "$ROOT_FILE"
    [ "$QUIET" = false ] && echo "Deleted: $ROOT_FILE"
  fi

  find "$FOLDER" -type f -name "exports_*.dart" | while read -r file; do
    if is_safe_to_delete "$file"; then
       rm "$file"
       [ "$QUIET" = false ] && echo "Deleted: $file"
    fi
  done
  
  [ "$QUIET" = false ] && echo "Done."
}

################################################################################
# Orchestrates the creation of the barrel files.
#
# Arguments:
#   None (Uses globals)
# Outputs:
#   Creates files and writes status to stdout.
################################################################################

perform_create() {
  if [ ! -d "$FOLDER" ]; then
    echo "Error: Folder '$FOLDER' does not exist."
    exit 1
  fi

  if [ "$QUIET" = false ]; then
    echo "--------------------------------------------------"
    echo "Creating barrel files..."
    echo "  Root: $ROOT_FILE"
    echo "  Scan: $FOLDER"
    echo "--------------------------------------------------"
  fi

  if [ "$YES" = false ]; then
    read -p "Create barrel files? [y/N] " -n 1 -r
    echo ""
    [[ $REPLY =~ ^[Yy]$ ]] || exit 0
  fi

  if [ "$FOLDER" = "." ]; then
    generate_recursive "." "$ROOT_FILE"
  else
    generate_recursive "$FOLDER" ""
    
    local inner_export="$FOLDER/exports_$(basename "$FOLDER").dart"
    {
      echo "$MAGIC_HEADER"
      echo ""
      echo "export \"$inner_export\";"
    } > "$ROOT_FILE"
  fi

  if [ "$QUIET" = false ]; then
    echo "Done."
  fi
}

################################################################################
# Main execution block.
#
# Arguments:
#   $@ - Command line arguments.
################################################################################

main() {
  parse_arguments "$@"
  determine_root_filename

  if [ "$VERB" = "create" ]; then
    perform_create
  elif [ "$VERB" = "delete" ]; then
    perform_delete
  else
    echo "Error: Invalid command '$VERB'."
    show_help
  fi
}

main "$@"