#!/usr/bin/env bash
set -euo pipefail

# install_scriptz.sh
#
# Installs scriptz tools by creating symlinks in /usr/local/bin (default)
# or ~/.local/bin (with --user-bin flag).
#
# Generates uninstall_scriptz.sh with the exact list of installed symlinks.
#
# Usage:
#   install_scriptz.sh           # Install to /usr/local/bin (requires sudo)
#   install_scriptz.sh --user-bin # Install to ~/.local/bin

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPTS_DIR="${SCRIPT_DIR}/scripts"
UNINSTALL_SCRIPT="${SCRIPT_DIR}/uninstall_scriptz.sh"

# Default to system-wide installation
BIN_DIR="/usr/local/bin"
USE_SUDO="sudo"

# Parse arguments
if [[ "${1:-}" == "--user-bin" ]]; then
    BIN_DIR="${HOME}/.local/bin"
    USE_SUDO=""
    mkdir -p "${BIN_DIR}"
fi

# Collect installed symlinks
declare -a INSTALLED_LINKS=()
NEW_COUNT=0
UPDATED_COUNT=0

echo "Installing scriptz to ${BIN_DIR}..."

# Find all tool folders and look for matching tool.sh or tool.py
for tool_dir in "${SCRIPTS_DIR}"/*/; do
    # Skip if not a directory
    [[ -d "${tool_dir}" ]] || continue
    
    tool_name="$(basename "${tool_dir}")"
    
    # Look for tool.sh first, then tool.py
    if [[ -f "${tool_dir}${tool_name}.sh" ]]; then
        tool_script="${tool_dir}${tool_name}.sh"
        link_name="${tool_name}"
    elif [[ -f "${tool_dir}${tool_name}.py" ]]; then
        tool_script="${tool_dir}${tool_name}.py"
        link_name="${tool_name}"
    else
        # No matching script found in this folder
        continue
    fi
    
    # Make the script executable
    chmod +x "${tool_script}"
    
    # Check if symlink already exists
    link_path="${BIN_DIR}/${link_name}"
    if [[ -L "${link_path}" ]]; then
        status="updated"
        ((UPDATED_COUNT++)) || true
    else
        status="new"
        ((NEW_COUNT++)) || true
    fi
    
    # Create symlink
    if [[ -n "${USE_SUDO}" ]]; then
        ${USE_SUDO} ln -sf "${tool_script}" "${link_path}"
    else
        ln -sf "${tool_script}" "${link_path}"
    fi
    
    # Track the created symlink
    INSTALLED_LINKS+=("${link_path}")
    
    echo "  [${status}] ${link_name} -> ${tool_script}"
done


# Generate uninstall script with embedded list
cat > "${UNINSTALL_SCRIPT}" << 'HEADER'
#!/usr/bin/env bash
set -euo pipefail

# uninstall_scriptz.sh
#
# Auto-generated by install_scriptz.sh
# Removes the symlinks that were created during installation.

HEADER

# Add the list of symlinks
echo "SYMLINKS=(" >> "${UNINSTALL_SCRIPT}"
for link in "${INSTALLED_LINKS[@]}"; do
    echo "    \"${link}\"" >> "${UNINSTALL_SCRIPT}"
done
echo ")" >> "${UNINSTALL_SCRIPT}"

# Add sudo detection
if [[ -n "${USE_SUDO}" ]]; then
    echo 'USE_SUDO="sudo"' >> "${UNINSTALL_SCRIPT}"
else
    echo 'USE_SUDO=""' >> "${UNINSTALL_SCRIPT}"
fi

# Add the uninstall logic
cat >> "${UNINSTALL_SCRIPT}" << 'FOOTER'

REMOVED_COUNT=0
NOT_FOUND_COUNT=0

echo "Uninstalling scriptz..."

for link_path in "${SYMLINKS[@]}"; do
    link_name="$(basename "${link_path}")"
    
    if [[ -L "${link_path}" ]]; then
        if [[ -n "${USE_SUDO}" ]]; then
            ${USE_SUDO} rm -f "${link_path}"
        else
            rm -f "${link_path}"
        fi
        echo "  Removed: ${link_name}"
        ((REMOVED_COUNT++)) || true
    else
        echo "  Not found: ${link_name}"
        ((NOT_FOUND_COUNT++)) || true
    fi
done

echo ""
echo "Uninstall complete."
echo "  Removed: ${REMOVED_COUNT}"
[[ ${NOT_FOUND_COUNT} -gt 0 ]] && echo "  Not found: ${NOT_FOUND_COUNT} (already removed?)"

# Self-delete
rm -f "$0"
echo "Uninstall script removed."
FOOTER

chmod +x "${UNINSTALL_SCRIPT}"

echo ""
echo "Installed ${#INSTALLED_LINKS[@]} scriptz tools to ${BIN_DIR}"
[[ ${NEW_COUNT} -gt 0 ]] && echo "  New: ${NEW_COUNT}"
[[ ${UPDATED_COUNT} -gt 0 ]] && echo "  Updated: ${UPDATED_COUNT}"
echo ""
echo "To uninstall, run: ${UNINSTALL_SCRIPT}"

